### ISSUE TITLE
Need detailed documentation for each parameter

### ISSUE THREAD

**Issue by paymicro** [Wheellog/Wheellog.Android#62]
in [wiki](https://github.com/Wheellog/Wheellog.Android/wiki)

**Comment by palachzzz** [comment]
Да уж, тут придётся поработать...

**Comment by paymicro** [comment]
Надо разбить на подзадачи

**Comment by bobpaul** [comment]
I don't have Wiki access. But here is a start for the English wiki

### Application Settings
These are general application settings. __Note__ Numeric settings can be adjusted either with the slider, or by tapping the number to directly enter a value.

- English
  - If enable, the application is forced to use English language instead of the Android system language
- Theme
  - Original or AJDM theme. Must restart to apply this change.
- Dark mode
  - Allows Forcing Dark mode, Light mode, or follow the phone settings
- Improved percents
  - If this is enabled, use Wheellog will calculate remaining battery percentage from the data logged during your ride. Otherwise, Wheellog will simply use the battery percentage provided by the wheel. Many EUC do not attempt to accurately calculating remaining battery and simply map battery voltage to a percentage. 
- Use MPH
  - Use Miles, MPH, etc instead of kilometers, km/h, etc.

**Main View**
These settings affect the main dashboard view of the application
- Info blocks
  - Choose the information blocks to show on the main screen. 
  - Text size of the info blocks will automatically adjust as more or fewer blocks are shown
- Notification buttons
  - While Wheellog is running, a persistent notification is shown to prevent the application from getting stopped by Android OS. Use this setting to choose which buttons (Connect/disconnect, Start/Stop logging, Connect/Disconnect from Watch, Beep Horn, Toggle Headlights, Mi Band)
- Top limit of outer dial
  - The outer dial is either Speed (km/h or mph) or Current (amps) (see next setting). This setting chooses the maximum value of the outer dial.
- Current on main dial
  - If enabled, display Current (amps) on the outer dial. Otherwise show Speed (km/h or mph)
- Short display of PWM
  - If enabled, PWM output (0% - 100%) is shown below the Spedometer. Otherwise, show the units of the Spedometer (km/h or mph)
- Events page
  - If enabled, the application Event log page is shown. This is useful for debugging. Swipe left/right to cycle between pages
- Trips page
  - If enabled, the Trips page is shown. This page contains a list of all of your recorded logs. Swipe left/right to cycle between pages. 
- Connect sound
  - Enable/disable the sound when connecting to the wheel
- Connection lost beeps period
  - How frequently to beep if connection to wheel is lost. Requires "Connect sound" is enabled. 0 sec = disable Connection lost beeps.
- Auto mute
  - Don't play sounds below 3.5km/h (2.2mph)
- Show Bluetooth without name
  - This is useful if your EUC shows as a device with only a numeric address.

**Beep**
These settings are for the Horn functionality.
- Beep horn on single tap
  - A single tap of the main screen will play a beep sound
- Beep on volume keys
  - Pressing the volume keys while Wheellog is active will play a beep sound. This will, of course, prevent the Volume keys from changing the volume.
- Beep by wheel
  - Play the horn sound through the wheel's speakers. On available on wheels with bluetooth speakers. Otherwise use the phone's speakers.
- Select beep file
  - Choose a file to use for the beep.

### Log Settings
- Auto Log
  - Logging will start automatically on connect
- Upload to electro.club
  - Automatically upload logs to electro.club for visualization. "Log Location" must be enabled.
- Use GPS for location
  - Use GPS for accurate location. Otherwise use location provided by network provider. Using GPS requires more power.
- Write Raw data
  - Generates a separate CSV file with the raw data received from the wheel.

### Alarm Settings
- Enable Alarms
  - Choose whether or not to enable the alarm functionality
- Disable Phone Vibration
  - Disable the Phone vibrations. If disabled, the phone will vibrate when an alarm is exceeded. This setting does not affect a connected watch. 
- Disable Phone Beep
  - Disable the Phone beeps. If disabled, the phone will plan alert sounds when an alarm is exceeded. This setting does not affect a connected watch.
- Altered Alarms
  - Enable advanced alarms based on battery voltage and wheel capabilities. This setting requires calibration using the free-spin speed of the wheel. Otherwise use alarms based on Speed and remaining Battery Percentage.

#### Standard Alarms
3 Speed alarms, 1 current alarm, and 1 temperature alarm are available. 

**Speed Alarms**
Speed alarms are activated  by exceeding the set speed  as long as the battery is at or below the set battery voltage. Speed Alarm 3 is the highest priority speed alarm.

Example
Speed 1 at 25km/h and 100%. Speed 2 at 30km/h and 100%. Speed 3 at 20km/h and 30%.
With this configuration, an alarm is always played when exceeding 25km/h. A higher priority alarm is played when exceeding 30km/h. And the highest priority alarm is played when exceeding 20km/h if the battery is at or below 30%.

**Current Alarm**
This is the current that triggers the alarm

**Temperature**
This is the temperature that triggers the alarm

#### Altered Alarms
Altered alarms are based on wheel PWM output. A PWM of 100% means the wheel is giving full power and hitting any minor bump or dip will result in a fall.
- Rotation Speed
  - Enter the speed your wheel rotates when lifted off the ground. This is required to calibrate the Altered Alarms
- Rotation voltage
  - Enter the voltage at which the rotation speed was measured. This is required to calibrate the Altered Alarms
- Power factor
  - Defaults to 90%. Do not adjust unless you understand the implications.
- First alarm PWM
  - This is the speed at which the first PWM alarm should occur. Defaults to 80%
- Second (and third) alarm PWM
  - Set the Second PWM alarm higher than the first and the Third PWM alarm higher than the second. These are higher priority alarms.
- Advanced warning Speed
  - Set a Speed for an advanced warning alert. 0 is off.
- Advanced warning PWM
  - Set a PWM for advanced warning. 0 is off.
- Frequency of Warnings
  - Set a period in seconds for how often advanced warnings should alert
- Current
  - Current that triggers the alarm; this is the same as the Current setting when using Standard alarms
- Temperature     
  - Temperature that triggers the alarm; this is the same as the Temperature setting when using Standard alarms

### Watch Preferences
These are settings for the Pebble and Garmin Watches
- Horn Mode
  - Pressing the button on the watch will activate the horn. Choose between Disabled, On-board horn (only on KingSong wheels), or horn via bluetooth audio
- Garmin ConnectIQ
  - Enable to connect to Garmin watch
  
### Wheel Settings
_Note_ Some of these settings are dependent on your wheel

- Light Mode
  - Adjust the headlight mode of the wheel (On, Off, Strobe)
- Alarm Mode
  - On Begode (Gotway) wheels, this setting allows disabling of the wheel's internal beep alarms at the first and second speed limit. The beep at 80% PWM cannot be disabled. Please see your owners manual for the speed and pattern (2 beeps/second, 3 beeps/second, etc) at which these alarms occur. This is unrelated to the Alarm section of the Wheellog settings.
- Pedals Mode
  - On Begode (Gotway) wheels, this provides Hard, Medium, and Soft pedal mode. This setting adjusts how quickly the wheel attempts to respond to road conditions and rider input. With Hard pedal mode, the wheel will respond as quickly as possible to keep the pedals flat. With Soft pedal mode, the wheel will take longer to correct tilt of the pedals caused by rider input and road conditions. The benefit is soft mode consumes slightly less battery.
- Wheel speed limit
  - This is the speed at which Tilt back will occur
- Wheel Calibration
  - Tap to start wheel calibration. Use this to adjust the angle of the pedals when riding.
- My Wheel is a Gotway MCM
  - Enable this setting to fix the speed, distance, and other parameters if you have a Gotway MCM and these values are incorrect
- Battery Voltage
  - Set the maximum battery voltage of your wheel.
- Negative current and speed mode
  - If current and speed are negative, enable this setting to invert the values so they show as positive in the app and logs
- Sound of connection
  - If enabled, the wheel will beep when Wheellog connects
- Battery Capacity
  - Enter the manufacturer specified capacity of the battery pack in Watt-hours.
- Charging power
  - Enter the maximum charge rate of the charger in Amps
- Edit Profile Name
  - Name the wheel you're connected to. This shows at the top of the Main dashboard screen
- MAC address
  - This is the bluetooth address of the connected wheel. You can't change this value

### Trip Settings
These options affect the logs stored in the wheel itself
- Reset top speed and PWM
  - Clear the lifetime max top speed and max PWM values saved in the wheel.
- Reset battery sag
  - Clear the lifetime minimum battery voltage value saved in the wheel
- Reset user distance
  - Clear the wheel's internal odometer.

**Comment by Hi-Angel** [comment]
@bobpaul 

> * Battery Capacity
>   
>   * Enter the manufacturer specified capacity of the battery pack in Watt-hours.

can you please clarify, what exactly this is for? Is this an internal setting in the app or is it somehow stored in the wheel? What changing that influences? It is `0` by default — why would I want to change it to actual number, and what's gonna happen if I change it to some 9999 Wh?

**Comment by bobpaul** [comment]
> can you please clarify, what exactly this is for? Is this an internal setting in the app or is it somehow stored in the wheel?

Battery capacity is a physical property of the battery. It's measured in watt-hours. Changing the capacity changes the remaining capacity estimation. I crashed my m10 a year ago so I can't currently play around with this, but the most accurate capacity estimation is to "coulomb count" (basically count milliamp-seconds or milliamp-tenthseconds) and sum your count, then subtract it from the battery's capacity. If you don't start with a completely full battery then you'll have to start your remaining capacity estimate based on the pack voltage (which can swing wildly as the motor load changes).
